config/routes.rb
Startupality::Application.routes.draw do
  root :to => 'angular#angular'
  match 'angular/angular' => 'angular#angular'

  match 'tags/:tag', to: 'angular#angular', as: :tag
  match 'tags', to: 'tags#index'

  resources :posts
  resources :tags
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable
  attr_accessible :text, :tag_list

  before_create :extract_tags_from_post

  def as_json(options = {})
    {
      :id => self.id,
      :text => self.text,
      :created_at => self.created_at,
      :updated_at => self.updated_at,
      :tags => self.tag_list
    }
  end

  private
    def extract_tags_from_post
      tags = []
      post_text = String.new(self.text)
      post_text.split.each do |word|
        tags << word.match(/[[:word:]-]+/).to_s if word.starts_with?"#"
      end
      self.tag_list = tags
    end
end

app/controllers/angular_controller.rb
class AngularController < ApplicationController
  def angular
    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
      # @posts = Post.tagged_with(params[:tag], :any => true)
    else
      @posts = Post.order("created_at DESC")
    end


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tag_counts = Post.tag_counts_on(:tags)
    @tags = []
    tag_cloud Post.tag_counts, %w(css1 css2 css3) do |tag, css_class|
      @tags << [tag, css_class]
    end
    render json: @tags
  end

  def tag_cloud(tags, classes)
    return [] if tags.empty?

    max_count = tags.sort_by(&:count).last.count.to_f

    tags.each do |tag|
      index = ((tag.count / max_count).to_f * (classes.size - 1))
      yield tag, classes[index.nan? ? 0 : index.round]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_div(kind)
		unless flash[kind].blank?
			text = "<p>#{flash[kind]}</p>"
			content_tag :div, text.html_safe, :id => "flash", :class => kind
		end
	end
	def current_navigation expected_path
		if params[:controller] ==expected_path
			return "active"
		else
			return ""
		end
	end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/angular/angular.html.erb
<div class="container" ng-app="mainapp">
    <div ng-controller="MainController">
        <div ng-include src="'<%= asset_path('partials/header.html') %>'">
        </div>
        <div id="main" ng-view></div>
        <div ng-include src="'<%= asset_path('partials/footer.html') %>'">
        </div>
    </div>
</div>

app/views/layouts/application.html.haml
!!!
%html{'xmlns:fb' => "http://ogp.me/ns/fb#"}
  %head
    %title Spottd.me
    %meta{'charset' => "utf-8"}
    %meta{'http-equiv' => "X-UA-Compatible", 'content' => "IE=edge,chrome=1"}
    %meta{'name' => "viewport", :content => "width=device-width, initial-scale=1"}
    %meta{'content' => "text/html; charset=UTF-8", 'http-equiv' => "Content-Type"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    <!--[if lte IE 8]><script src="assets/lib/angular-ui-ieshiv.js"></script><![endif]-->
    = csrf_meta_tags
    = yield :header
  %body{:id => "%s_%s" % [controller_name, action_name]}
    #fb-root
    :javascript
      (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "http://connect.facebook.net/en_US/all.js#xfbml=1&appId=144861229023265";
          fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    / = render "layouts/header"
    = yield
    = yield :footer

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.text_field :text %>
  </div>

  <div class="form-inputs">
    <%= f.label :tag_list, "Tags (separated by commas)" %>
    <%= f.text_field :tag_list %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.text %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @post.text %>
</p>

<p>
  <% if !@post.tag_list.blank? %>
    <p>Tags: <%= raw @post.tag_list.map { |tag| link_to tag, tag_path(tag) }.join(', ') %></p>
  <% end %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>